# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_transport import core_pb2 as core__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in core_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DecisionIntelligenceCoreStub:
    """Decision Intelligence Framework v1.2 - Core Specification, section 1.7.
    Same 3 methods as the REST API (api/main.py) - both transports call into
    the same application layer, see grpc/server.py.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateMetric = channel.unary_unary(
                '/decisionintelligence.core.v1.DecisionIntelligenceCore/UpdateMetric',
                request_serializer=core__pb2.UpdateMetricRequest.SerializeToString,
                response_deserializer=core__pb2.UpdateMetricResponse.FromString,
                _registered_method=True)
        self.GetScoreboard = channel.unary_unary(
                '/decisionintelligence.core.v1.DecisionIntelligenceCore/GetScoreboard',
                request_serializer=core__pb2.GetScoreboardRequest.SerializeToString,
                response_deserializer=core__pb2.ScoreboardState.FromString,
                _registered_method=True)
        self.GetMerkleProof = channel.unary_unary(
                '/decisionintelligence.core.v1.DecisionIntelligenceCore/GetMerkleProof',
                request_serializer=core__pb2.GetMerkleProofRequest.SerializeToString,
                response_deserializer=core__pb2.MerkleProof.FromString,
                _registered_method=True)


class DecisionIntelligenceCoreServicer:
    """Decision Intelligence Framework v1.2 - Core Specification, section 1.7.
    Same 3 methods as the REST API (api/main.py) - both transports call into
    the same application layer, see grpc/server.py.

    """

    def UpdateMetric(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScoreboard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMerkleProof(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DecisionIntelligenceCoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateMetric': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMetric,
                    request_deserializer=core__pb2.UpdateMetricRequest.FromString,
                    response_serializer=core__pb2.UpdateMetricResponse.SerializeToString,
            ),
            'GetScoreboard': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScoreboard,
                    request_deserializer=core__pb2.GetScoreboardRequest.FromString,
                    response_serializer=core__pb2.ScoreboardState.SerializeToString,
            ),
            'GetMerkleProof': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMerkleProof,
                    request_deserializer=core__pb2.GetMerkleProofRequest.FromString,
                    response_serializer=core__pb2.MerkleProof.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'decisionintelligence.core.v1.DecisionIntelligenceCore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('decisionintelligence.core.v1.DecisionIntelligenceCore', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DecisionIntelligenceCore:
    """Decision Intelligence Framework v1.2 - Core Specification, section 1.7.
    Same 3 methods as the REST API (api/main.py) - both transports call into
    the same application layer, see grpc/server.py.

    """

    @staticmethod
    def UpdateMetric(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/decisionintelligence.core.v1.DecisionIntelligenceCore/UpdateMetric',
            core__pb2.UpdateMetricRequest.SerializeToString,
            core__pb2.UpdateMetricResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScoreboard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/decisionintelligence.core.v1.DecisionIntelligenceCore/GetScoreboard',
            core__pb2.GetScoreboardRequest.SerializeToString,
            core__pb2.ScoreboardState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMerkleProof(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/decisionintelligence.core.v1.DecisionIntelligenceCore/GetMerkleProof',
            core__pb2.GetMerkleProofRequest.SerializeToString,
            core__pb2.MerkleProof.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
